# Generated by Django 5.1.7 on 2025-04-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slavichoney_app', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
